In [3]:
import numpy as np
import scipy as sp

def update_b(z, residues, poles, constant):
    
    np.sum(residues/(z-poles)) + constant
        
def vector_fitting(input_data, output_data, initial_poles, iterations):
    
    """
    Notice that we use the first term in the vector for the constant c^{i+1}
    """
    z = input_data
    y = output_data
    
    n_data_points = z.size
    n_poles = len(initial_poles)
    
    #print(n_poles)
    A = np.zeros((iterations, n_data_points, 2*n_poles+1), dtype='complex128')
    A[:,:,0] = 1
    
    poles = np.zeros((iterations, n_poles), dtype = 'complex128')
    poles[0,:] = initial_poles
    
    r = np.ones((iterations,n_poles))
    #r[0] = [1]*n_poles
    for i in range(iterations):
        for k in range(n_data_points):
            for n in range(1,n_poles):
                #print(i,k,n)
                A[i,k,n] = 1/(z[k] - poles[i,n])
                A[i,k,n+n_poles-1] = -y[k]/(z[k] - poles[i,n])
        #print(A[i,:,:].shape)
        #print(y.shape)
        solution = np.linalg.lstsq(A[i,:,:], y)[0]
        #solutions[i] = solution
        
        r[i+1,:] = solution[1:n_poles]
        r[i,:] = solution[n_poles+1:]
        
        print(poles[i,:])
        print(r[i+1,:].shape)
        # Update poles by finding root of 
        poles[i+1,:] = scipy.optimize.root(update_b, poles[i,:], args=(r[i+1,:], poles[i,:], solution[0]))
                
    return p    
                
            

#F[i,k,n] = R[i,n]/(z[k] - p[i,n]) + c[i]

#b[i,k,n] = r[i+1, n]/(z[k] - p[i,n]) + c[i+1]

Z = np.loadtxt('training_data/test/X.txt')
Y = np.loadtxt('training_data/test/noised_data.txt')
true_poles = np.loadtxt('training_data/test/poles.txt')
fitted_poles = vector_fitting(Z, Y, [2+4j, 5], 3)

[2.+4.j 5.+0.j]
(2,)
<ipython-input-3-357d6bc362f0>:36: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution = np.linalg.lstsq(A[i,:,:], y)[0]
<ipython-input-3-357d6bc362f0>:39: ComplexWarning: Casting complex values to real discards the imaginary part
  r[i+1,:] = solution[1:n_poles]
<ipython-input-3-357d6bc362f0>:40: ComplexWarning: Casting complex values to real discards the imaginary part
  r[i,:] = solution[n_poles+1:]


AttributeError: module 'scipy' has no attribute 'optimize'

In [4]:
X

NameError: name 'X' is not defined

In [23]:
import numpy as np

x = np.array(np.zeros((3,2)))
x + 1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
n = 2
lol = np.zeros((3,4,5))
lol[1,:,:]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
lol = np.zeros((3,3), dtype = 'complex128')

In [82]:
mat = np.array([[3,1],[1,2]])
lol1 = np.array([9,8])
np.linalg.lstsq(mat, lol1, rcond =None)

(array([2., 3.]), array([], dtype=float64), 2, array([3.61803399, 1.38196601]))

In [84]:
mat.dot([2,3])

array([9, 8])

In [87]:
[1]*2

[1, 1]